module.exports = {
  content: ["_site/**/*.html", "_site/**/*.js"],
  css: ["_site/assets/css/*.css"],
  output: "_site/assets/css/",
  skippedContentGlobs: ["_site/assets/**/*.html"],
  safelist: [
    "row",
    "col-sm-6",
    "col-lg-4",
    "col-sm",
    "col-md",
    "mt-3",
    "my-5",
    "about-post",
    "name-native",
    "subtitle-school-logo",
    "subtitle-school-logo-umn",
    "about-inline-affiliation-link",
    "about-inline-brand-icon",
    "about-inline-brand-icon-umn",
    "profile-contact-inline",
    "profile-email-line",
    "profile-social-links-line",
    "profile-social-link",
    "profile-social-sep",
    "brand-icon",
    "brand-icon-linkedin",
    "brand-icon-gmail",
  ],
};
